services:
  - type: web
    name: casual-character-chat
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node index.js"
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false